version: '3.8'

services:
  proxy:
    container_name: proxy
    image: nginx:1.19-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - backend
    depends_on:
      - mysql
      - adonis_app
  mysql:
    build:
      context: ./mysql
    container_name: mysql
    environment:
      - MYSQL_USER=${MYSQL_DOCKER_USER}
      - MYSQL_PASSWORD=${MYSQL_DOCKER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_DOCKER_ROOT_PASSWORD}
      - TZ=${APP_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    networks:
      - backend

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - mysql
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
    volumes:
      - ./:/home/node/app
    networks:
      - backend
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

networks:
  backend:
    name: 'backend'
    driver: bridge
